### ISSUE TITLE
document use of nginx accelleration

### ISSUE THREAD

**Issue by karcaw** [pacifica/pacifica-proxy#24]
### Pacifica Proxy version
master

### Platform Details
all

### Scenario:
understant how to use the nginx acceleration options

### Steps to Reproduce:
look in docs, no mention of it.  look in code it seems to have it in the config.py and in the file.py 

### Expected Result:
I would see details about the options and how to use them

### Actual Result:
No documentation found

**Comment by dmlb2000** [comment]
@karcaw did you check out Travis CI config? That should get you started, if you are stuck.

**Comment by karcaw** [comment]
Not stuck, just noticed it's not documented.
